quadrotor_env:
   camera: no
   sim_dt: 0.02 
   max_t: 5.0
   add_camera: no

quadrotor_dynamics:
  mass: 2.0
  arm_l: 0.21
  motor_omega_min: 150.0 # motor rpm min
  motor_omega_max: 1000.0 # motor rpm max
  motor_tau: 0.05 # motor step response
  motor_tau_up: 0.0125 # motor step up response
  motor_tau_down: 0.025 # motor step down response
  thrust_map: [1.3298253500372892e-06, 0.0038360810526746033, -1.7689986848125325]
  kappa: 0.016 # rotor drag coeff
  omega_max: [6.0, 6.0, 6.0]  # body rate constraint (x, y, z) 

rl:
  pos_coeff: -0.0065        # reward coefficient for position #-0.002
  ori_coeff: -0.002        # reward coefficient for orientation
  lin_vel_coeff: -0.0002   # reward coefficient for linear velocity
  ang_vel_coeff: -0.0002   # reward coefficient for angular velocity
  act_coeff: -0.0002  # reward coefficient for control actions
  omega_coeff: -0.002
  yaw_coeff: -0.002
  pos_coeff_exp: 0.025 #0.25
  exp_coeff_pos: -2.0 #-0.5
  ori_coeff_exp: 0.004 #0.005
  exp_coeff_ori: -8.2 #-5